### ISSUE TITLE
Native Code compile failed

### ISSUE THREAD

**Issue by TimDix** [agentk/gulp-fontgen#6]
Im getting the following error when installing gulp-fontgen, but I cant figure out if its a problem with gulp-fontgen or execsync, any thoughts on this?

>execSync@1.0.2 install /mydirectory/node_modules/gulp-fontgen/node_modules/fontfacegen/node_modules/execSync
> node install.js

>[execsync v1.0.2] Attempting to compile native extensions.
>[execSync v1.0.2]
>   Native code compile failed!!
>gulp-fontgen@0.1.4 ../node_modules/gulp-fontgen
>├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
>├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.0, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.3.0, multipipe@0.1.2, dateformat@1.0.11)
>└── fontfacegen@0.1.4 (mkdirp@0.3.5, execSync@1.0.2)

**Comment by timdix** [comment]
This appears to be an issue with fontfacegen that your are requiring to be a dependancy. More specifically, execSync no longer works and and fontfacegen depends on it. A patch was issued to the maintainers of fontfacegen 14 days ago but it doesnt look like they are actively maintaining it.

**Comment by agentk** [comment]
Hi @TimDix, very sorry about that. I had to take a break for a while. fontfacegen has been updated to remove the dependency on exec sync. I'm pushing out npm updates now.
